from __future__ import annotations
import pylibmgm
from pylibmgm import io, solver
import typing

__all__ = ['CostMap', 'GMLocalSearcher', 'GMLocalSearcherParallel', 'GmModel', 'GmSolution', 'Graph', 'LAPSolver', 'MgmGenerator', 'MgmModel', 'MgmSolution', 'ParallelGenerator', 'QAPSolver', 'SequentialGenerator', 'SwapLocalSearcher', 'build_sync_problem', 'omp_set_num_threads', 'io', 'solver']

class CostMap:
    @typing.overload
    def contains(self: pylibmgm.CostMap, node1: int, node2: int) -> bool:
        ...
    @typing.overload
    def contains(self: pylibmgm.CostMap, assignment: tuple[int, int]) -> bool:
        ...
    @typing.overload
    def contains(self: pylibmgm.CostMap, node1_left: int, node2_left: int, node1_right: int, node2_right: int) -> bool:
        ...
    @typing.overload
    def contains(self: pylibmgm.CostMap, edge: tuple[tuple[int, int], tuple[int, int]]) -> bool:
        ...
    @typing.overload
    def pairwise(self: pylibmgm.CostMap, node1_left: int, node2_left: int, node1_right: int, node2_right: int) -> float:
        ...
    @typing.overload
    def pairwise(self: pylibmgm.CostMap, edge: tuple[tuple[int, int], tuple[int, int]]) -> float:
        ...
    @typing.overload
    def unary(self: pylibmgm.CostMap, node1: int, node2: int) -> float:
        ...
    @typing.overload
    def unary(self: pylibmgm.CostMap, assignment: tuple[int, int]) -> float:
        ...
class GMLocalSearcher:
    @typing.overload
    def __init__(self: pylibmgm.GMLocalSearcher, model: MgmModel) -> None:
        ...
    @typing.overload
    def __init__(self: pylibmgm.GMLocalSearcher, model: MgmModel, matching_order: list[int]) -> None:
        ...
    def search(self: pylibmgm.GMLocalSearcher, solution: MgmSolution) -> bool:
        ...
class GMLocalSearcherParallel:
    def __init__(self: pylibmgm.GMLocalSearcherParallel, model: MgmModel, merge_all: bool = True) -> None:
        ...
    def search(self: pylibmgm.GMLocalSearcherParallel, solution: MgmSolution) -> bool:
        ...
class GmModel:
    graph1: Graph
    graph2: Graph
    @typing.overload
    def __init__(self: pylibmgm.GmModel, graph1: Graph, graph2: Graph) -> None:
        ...
    @typing.overload
    def __init__(self: pylibmgm.GmModel, graph1: Graph, graph2: Graph, no_assignments: int, no_edges: int) -> None:
        ...
    def add_assignment(self: pylibmgm.GmModel, node1: int, node2: int, cost: float) -> None:
        ...
    @typing.overload
    def add_edge(self: pylibmgm.GmModel, assignment1: int, assignment2: int, cost: float) -> None:
        """
        Add an edge via two assignment ids
        """
    @typing.overload
    def add_edge(self: pylibmgm.GmModel, node1_left: int, node2_left: int, node1_right: int, node2_right: int, cost: float) -> None:
        """
        Add an edge via four node ids
        """
    def costs(self: pylibmgm.GmModel) -> CostMap:
        ...
    def no_assignments(self: pylibmgm.GmModel) -> int:
        ...
    def no_edges(self: pylibmgm.GmModel) -> int:
        ...
    @property
    def assignment_list(self) -> list[tuple[int, int]]:
        ...
class GmSolution:
    model: GmModel
    @staticmethod
    def evaluate_static(model: GmModel, labeling: list[int]) -> float:
        ...
    def __getitem__(self: pylibmgm.GmSolution, node_id: int) -> int:
        ...
    @typing.overload
    def __init__(self: pylibmgm.GmSolution) -> None:
        ...
    @typing.overload
    def __init__(self: pylibmgm.GmSolution, model: GmModel) -> None:
        ...
    @typing.overload
    def __init__(self: pylibmgm.GmSolution, model: GmModel, labeling: list[int]) -> None:
        ...
    def __setitem__(self: pylibmgm.GmSolution, node_id: int, label: int) -> None:
        ...
    def evaluate(self: pylibmgm.GmSolution) -> float:
        ...
    def labeling(self: pylibmgm.GmSolution) -> list[int]:
        ...
    def to_list_with_none(self: pylibmgm.GmSolution) -> list:
        ...
class Graph:
    id: int
    no_nodes: int
    def __init__(self: pylibmgm.Graph, graph_id: int, no_nodes: int) -> None:
        ...
class LAPSolver:
    def __init__(self: pylibmgm.LAPSolver, model: GmModel) -> None:
        ...
    def run(self: pylibmgm.LAPSolver) -> GmSolution:
        ...
class MgmGenerator:
    class matching_order:
        """
        Members:
        
          sequential
        
          random
        """
        __members__: typing.ClassVar[dict[str, MgmGenerator.matching_order]]  # value = {'sequential': <matching_order.sequential: 0>, 'random': <matching_order.random: 1>}
        random: typing.ClassVar[MgmGenerator.matching_order]  # value = <matching_order.random: 1>
        sequential: typing.ClassVar[MgmGenerator.matching_order]  # value = <matching_order.sequential: 0>
        def __eq__(self, other: typing.Any) -> bool:
            ...
        def __getstate__(self) -> int:
            ...
        def __hash__(self) -> int:
            ...
        def __index__(self) -> int:
            ...
        def __init__(self, value: int) -> None:
            ...
        def __int__(self) -> int:
            ...
        def __ne__(self, other: typing.Any) -> bool:
            ...
        def __repr__(self) -> str:
            ...
        def __setstate__(self, state: int) -> None:
            ...
        def __str__(self) -> str:
            ...
        @property
        def name(self) -> str:
            ...
        @property
        def value(self) -> int:
            ...
    random: typing.ClassVar[MgmGenerator.matching_order]  # value = <matching_order.random: 1>
    sequential: typing.ClassVar[MgmGenerator.matching_order]  # value = <matching_order.sequential: 0>
class MgmModel:
    graphs: list[Graph]
    models: dict[tuple[int, int], GmModel]
    no_graphs: int
    def __init__(self: pylibmgm.MgmModel) -> None:
        ...
    def add_model(self: pylibmgm.MgmModel, gm_model: GmModel) -> None:
        ...
    def create_submodel(self: pylibmgm.MgmModel, graph_ids: list[int]) -> pylibmgm.MgmModel:
        ...
class MgmSolution:
    model: MgmModel
    def __getitem__(self: pylibmgm.MgmSolution, graph_pair: tuple[int, int]) -> list[int]:
        ...
    def __init__(self: pylibmgm.MgmSolution, model: MgmModel) -> None:
        ...
    def __len__(self: pylibmgm.MgmSolution) -> int:
        ...
    def __setitem__(self: pylibmgm.MgmSolution, graph_pair: tuple[int, int], labeling: list[int]) -> None:
        ...
    def cliques(self: pylibmgm.MgmSolution) -> list[dict]:
        ...
    def create_empty_labeling(self: pylibmgm.MgmSolution) -> dict[tuple[int, int], list[int]]:
        ...
    @typing.overload
    def evaluate(self: pylibmgm.MgmSolution) -> float:
        ...
    @typing.overload
    def evaluate(self: pylibmgm.MgmSolution, graph_id: int) -> float:
        ...
    def labeling(self: pylibmgm.MgmSolution) -> dict[tuple[int, int], list[int]]:
        ...
    @typing.overload
    def set_solution(self: pylibmgm.MgmSolution, labeling: dict[tuple[int, int], list[int]]) -> None:
        ...
    @typing.overload
    def set_solution(self: pylibmgm.MgmSolution, graph_pair: tuple[int, int], labeling: list[int]) -> None:
        ...
    @typing.overload
    def set_solution(self: pylibmgm.MgmSolution, gm_solution: GmSolution) -> None:
        ...
    def to_dict_with_none(self: pylibmgm.MgmSolution) -> dict:
        ...
class ParallelGenerator(MgmGenerator):
    def __init__(self: pylibmgm.ParallelGenerator, model: MgmModel) -> None:
        ...
    def generate(self: pylibmgm.ParallelGenerator) -> MgmSolution:
        ...
    def init(self: pylibmgm.ParallelGenerator, order: MgmGenerator.matching_order) -> list[int]:
        ...
class QAPSolver:
    class RunSettings:
        batch_size: int
        greedy_generations: int
        def __init__(self: pylibmgm.QAPSolver.RunSettings) -> None:
            ...
    class StoppingCriteria:
        p: int
        k: int
        max_batches: int
        def __init__(self: pylibmgm.QAPSolver.StoppingCriteria) -> None:
            ...
    run_settings: RunSettings
    stopping_criteria: StoppingCriteria
    default_run_settings: typing.ClassVar[RunSettings]
    default_stopping_criteria: typing.ClassVar[StoppingCriteria]
    libmpopt_seed: typing.ClassVar[int]
    def __init__(self, model: GmModel) -> None:
        ...
    def run(self, verbose: bool = False) -> GmSolution:
        ...
class SequentialGenerator(MgmGenerator):
    def __init__(self: pylibmgm.SequentialGenerator, model: MgmModel) -> None:
        ...
    def generate(self: pylibmgm.SequentialGenerator) -> MgmSolution:
        ...
    def init(self: pylibmgm.SequentialGenerator, order: MgmGenerator.matching_order) -> list[int]:
        ...
    def step(self: pylibmgm.SequentialGenerator) -> None:
        ...
class SwapLocalSearcher:
    def __init__(self: pylibmgm.SwapLocalSearcher, model: MgmModel) -> None:
        ...
    def search(self: pylibmgm.SwapLocalSearcher, solution: MgmSolution) -> bool:
        ...
def build_sync_problem(model: MgmModel, solution: MgmSolution, feasible: bool = True) -> MgmModel:
    ...
def omp_set_num_threads(num_threads: int) -> None:
    ...